### ISSUE TITLE
option "openright"

### ISSUE THREAD

**Issue by dgalcius** [vtex-soft/texsupport.elsevier-book#42]
Take into account  option "openright". Print chapter opening page on odd page.

**Comment by dgalcius** [comment]
Fixed. This is a default behaviour.

**Comment by Rudi000** [comment]
Now Chapters begin on odd-numbered pages, but the table of contents still lists an even numbered page. Also navigating using Adobe's table of contents brings one to an empty page.

**Comment by dgalcius** [comment]
I cannot reproduce the issue on my machine. Please could you share a zip file (stripped down version or
minimal (non-)working example) that I could work on. The best option is to put a zip file on some cloud-based sharing services, and share a link. Please include a log file in a zip file as well.

**Comment by Rudi000** [comment]
Please find my minimal example in this directory. The log file is in the TeXAux directory.

If you click on Chapter 1 or Chapter 3 in the Table of Contents (or in Adobe Acrobat) you are put on the correct page, but if you click on Chapter 2 you are out on the previous (empty, even-numbered) page.

The behavior is different if I use \input instead of \include. In that case clicking on Chapter 3 puts you right after the end of the text in Chapter 2.

There is also an inexplicable gap in the Table of Contents before Chapter 2 when one uses \include. This does not happen with \input.

**Comment by dgalcius** [comment]
Please could you post your zip file via github interface. 
All attachments sent by email are removed by github. 
Thank you.

**Comment by Rudi000** [comment]
Does this work? 

[mwe.zip](https://github.com/vtex-soft/texsupport.elsevier-book/files/14421687/mwe.zip)

**Comment by dgalcius** [comment]
Perfectly. Thank you.
Please enclose `\chapter{..}` in `{frontmatter}` environment. E.g., 

```
\begin{frontmatter}
\chapter{...}
\end{frontmatter}
```
This should fix the issue.

**Comment by Rudi000** [comment]
Thank you! This seems to work. 

Is this the final solution or a temporary workaround?

**Comment by Rudi000** [comment]
It now jumps to the right place but the page numbers in the Table of Contents are still wrong.

**Comment by dgalcius** [comment]
As per template there should be `\begin{frontmatter}...\end{frontmatter}`. So this is not temporary. 
Closing.
Thank you.
